# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: Default 
  vmImage: ubuntu-latest

steps:
- task: Print@0
  displayName: Print text

- script: echo "Hello world"
  displayName: Print Hello World

- script: |
    echo "##vso[task.complete result=Succeeded]" # Mark the task as succeeded
  condition: always()